### ISSUE TITLE
Creating an exception when voteparty is started.

### ISSUE THREAD

**Issue by Kekkakarot** [GeorgeV22-ArtlieX/VoteRewards#8]
>....       [16:05:12 WARN: [VoteRewards] Starting VoteParty]
>....       [16:05:12 WARN: [VoteRewards] Plugin VoteRewards v2.2.0-Beta generated an exception while executing task 1266]
java.lang.IllegalStateException: VotePartyStartEvent may only be triggered synchronously.
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.14.4.jar:git-Paper-175]
    at com.GeorgeV22.VoteRewards.Utilities.VoteParty$3.run(VoteParty.java:210) ~[?:?]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
    at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-175]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-175]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

**Comment by GeorgeV22-ArtlieX** [comment]
Can you tell me what spigot you are using?
