### ISSUE TITLE
Votetop Command generates exception

### ISSUE THREAD

**Issue by lancehutchinson** [GeorgeV22-ArtlieX/VoteRewards#9]
There is an error when using the command /votetop

`[15:46:44] [Server thread/WARN]: Unexpected exception while parsing console command "votetop"
org.bukkit.command.CommandException: Unhandled exception executing command 'votetop' in plugin VoteRewards v2.2.0-Beta
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:695) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.GeorgeV22.VoteRewards.Utilities.UUIDFetcher.getName(UUIDFetcher.java:96) ~[?:?]
	at com.GeorgeV22.VoteRewards.Utilities.UUIDFetcher.getName(UUIDFetcher.java:105) ~[?:?]
	at com.GeorgeV22.VoteRewards.Utilities.Votes.getTopVotePlayer(Votes.java:231) ~[?:?]
	at com.GeorgeV22.VoteRewards.Commands.VoteTop.onCommand(VoteTop.java:30) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	... 8 more`

**Comment by GeorgeV22-ArtlieX** [comment]
You probably have a corrupted uuid inside your data.yml. This will be fixed in the new version
